import os
from datetime import datetime
from docx import Document
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT

OUTPUT_DIR = os.path.expanduser("~/hackblr-legal-ai/generated_docs")
os.makedirs(OUTPUT_DIR, exist_ok=True)

def generate_legal_notice(sender_name, sender_address, recipient_name, recipient_address, subject, body, demands):
    doc = Document()
    title = doc.add_heading("LEGAL NOTICE", level=0)
    title.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
    dp = doc.add_paragraph()
    dp.alignment = WD_PARAGRAPH_ALIGNMENT.RIGHT
    dp.add_run(f"Date: {datetime.now().strftime('%d/%m/%Y')}").bold = True
    doc.add_paragraph()
    doc.add_paragraph().add_run("FROM:").bold = True
    doc.add_paragraph(sender_name)
    doc.add_paragraph(sender_address)
    doc.add_paragraph()
    doc.add_paragraph().add_run("TO:").bold = True
    doc.add_paragraph(recipient_name)
    doc.add_paragraph(recipient_address)
    doc.add_paragraph()
    doc.add_paragraph().add_run(f"SUBJECT: {subject}").bold = True
    doc.add_paragraph()
    doc.add_paragraph(body)
    if demands:
        doc.add_paragraph()
        doc.add_paragraph().add_run("DEMANDS:").bold = True
        for i, d in enumerate(demands, 1):
            doc.add_paragraph(f"{i}. {d}", style="List Number")
    doc.add_paragraph()
    doc.add_paragraph("You are hereby called upon to comply with the above demands within 15 days of receipt of this notice, failing which my client shall initiate appropriate legal proceedings at your risk, cost, and consequences.")
    doc.add_paragraph()
    doc.add_paragraph("Yours truly,")
    doc.add_paragraph(sender_name)
    doc.add_paragraph()
    doc.add_paragraph().add_run("DISCLAIMER: AI-generated document. Have it reviewed by a qualified lawyer before use.").italic = True
    filename = f"legal_notice_{datetime.now().strftime('%Y%m%d_%H%M%S')}.docx"
    filepath = os.path.join(OUTPUT_DIR, filename)
    doc.save(filepath)
    return filepath

def generate_contract_review_report(contract_name, analysis, recommendations):
    doc = Document()
    doc.add_heading("CONTRACT REVIEW REPORT", level=0)
    doc.add_paragraph(f"Document: {contract_name}")
    doc.add_paragraph(f"Review Date: {datetime.now().strftime('%d/%m/%Y')}")
    doc.add_paragraph("Generated by: LegalAI Agent (HackBLR)")
    doc.add_heading("Analysis", level=1)
    doc.add_paragraph(analysis)
    if recommendations:
        doc.add_heading("Recommendations", level=1)
        for rec in recommendations:
            doc.add_paragraph(rec, style="List Bullet")
    doc.add_paragraph()
    doc.add_paragraph().add_run("DISCLAIMER: AI-generated analysis. Not a substitute for professional legal advice.").italic = True
    filename = f"contract_review_{datetime.now().strftime('%Y%m%d_%H%M%S')}.docx"
    filepath = os.path.join(OUTPUT_DIR, filename)
    doc.save(filepath)
    return filepath
